### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by anbraten** [kiel-live/kiel-live#252]
- [ ] add multiple transportation types / collectors
  - [x] bus (stop & vehicle)
  - [ ] tram (stop & vehicle)
  - [ ] bike (vehicle at stop)
  - [ ] e-scooter (vehicle)
  - [ ] car-sharing (vehicle)
  - [ ] train (stop & vehicle)
  - [ ] ferry (stop & vehicle)
  - [ ] sub-way (stop & vehicle)
  - [ ] bike-repair stations (poi) #240
  - [ ] gas-stations (poi)
- [ ] add filter for transportation types
- [ ] search 
  - [ ] search for stops from all collectors
  - [ ] search for street names / pois
- [ ] navigation
  - [ ] navigate from stop to stop
  - [ ] navigate from address / stop to address / stop
  - [ ] navigate only using specific transportation types
  - [ ] add option to walk

**Comment by anbraten** [comment]
That is definitely somehow my plan as well. While searching for good data formats and sources I discovered gtfs, gtfs-rt and gbfs to be the most used ones and motis / the work on transitious seems to be quite perfectly fitting as a data source.

**Comment by kalon33** [comment]
Your interface as a front UI to MOTIS and/or Transitous would be awesome! That's something important that is currently missing imho.
